### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by dazza041** [Regulus343/Fractal#2]
Hi!

I've tried installing the L4 version to no avail. Keep getting this error - "The requested package regulus/fractal 1.0.0 could not be found."

Any ideas?

**Comment by Regulus343** [comment]
Is your require line in composer.json including 0.8.2?

"require": {
    "regulus/fractal": "0.8.2"
},

There is no 1.0.0 release yet for Fractal, so you will have to use the latest that will exist for Laravel 4 which is 0.8.2.

**Comment by dazza041** [comment]
Sure did.

Heres the output from Terminal:

composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package regulus/fractal 1.0.0 could not be found.
  Problem 2
    - Installation request for regulus/fractal 0.8.2 -> satisfiable by regulus/fractal[v0.8.2].
    - regulus/fractal v0.8.2 requires maxhoffmann/parsedown-laravel @dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

![screen shot 2015-03-20 at 17 08 14](https://cloud.githubusercontent.com/assets/4716752/6756730/b8eff92a-cf23-11e4-8b5b-d187ea1e39d5.png)

**Comment by Regulus343** [comment]
It seems that "regulus/fractal" is in the require line of its own composer.json and not Laravel's. Is that the case? My Laravel 4 composer.json "require" looks like this:

"require": {
	"laravel/framework": "4.2.x",
	"regulus/identify": "dev-master",
	"regulus/fractal": "dev-master"
},

And my Fractal composer.json is left with what is already in it in the 0.8.2 release: https://github.com/Regulus343/Fractal/blob/v0.8.2/composer.json

Perhaps I am misunderstanding something about your setup? You shouldn't have to edit any files in the actual Fractal repository. Including it in Laravel's composer.json file and running composer update should be enough.
